# Setup
name:         Ingenierong
tagline:      Embedded System and Firmware development
#baseurl:      "https://ingenierong.github.io"
locale:       "es"
#url:	      "https://ingenierong.github.io/"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

collections:
 portfolio:
  output: true
  permalink: /portfolio/:path/