# Setup
name:         Ingenierong
tagline:      Embedded System and Firmware development
baseurl:      "http://protocop.es"
locale:       "es"
url:	      "https://ingenierong.github.io/"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

collections:
 portfolio:
  output: true
  permalink: /portfolio/:path/
